title: Tamara Ramsay
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#url: "http://tamararamsay.com"
url: "http://tamara-v2.s3-website-us-west-2.amazonaws.com"

tabs:
  - title: Allergies
    link: ""
  - title: Recipies
    link: recipies.html
  - title: Blog
    layout: blog

markdown: kramdown
