---
label: Recipe
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: list
  name: ingredients
  label: ingredients
- type: list
  name: instructions
  label: instructions
- type: datetime
  name: date
  label: date
